### ISSUE TITLE
doesn't work with python 3.12

### ISSUE THREAD

**Issue by hemantbhai100** [fja05680/pinkfish#92]
AppData\Local\Temp\easy_install-ai3jw5rk\empyrical-0.5.5\versioneer.py", line 412, in get_config_from_root
AttributeError: module 'configparser' has no attribute 'SafeConfigParser'

**Comment by fja05680** [comment]
Hi, try upgrading to at least python 3.10.12.  I recommend using a python virtual environment as well.  This should work for you.  I don't have time to support older versions of python.

**Comment by fja05680** [comment]
Closing this issue.
